let a = 6;
let b = 3;
console.log("a =",a,"b =",b,"Condition a>b -",a>b);
a = 3;
b = 3;
console.log("a =",a,"b =",b,"Condition a==b -",a==b);
a = 3;
b = 6;
console.log("a =",a,"b =",b,"Condition a!=b -",a!=b);
a = 1;
b = "";
console.log("a =",a,"b =",b,"Condition a===b -",a===b);
a="B";
b="A";
console.log("B>A -",a>b);
a="a";
b="Z";
console.log("a>Z -",a>b);
a=false;
b=0;
console.log("a =",a,"b =",b,"Condition a>=b -",a>=b);
a=("2"===2)?"ok":"not";
console.log(a);